knp_paginator:
  page_range: 5 # Nombre de pages maximum affichées dans la pagination
  default_options:
    page_name: page # Le nom du paramètre de requête utilisé pour la page
    sort_field_name: sort # Le nom du paramètre de requête utilisé pour le tri
    sort_direction_name: direction # Le nom du paramètre de requête utilisé pour la direction de tri
    distinct: true # Définissez-le sur true si vous avez besoin de pagination distincte (pour DISTINCT queries)
